### ISSUE TITLE
I would like an option to hide from public the transactions I sent

### ISSUE THREAD

**Issue by bitcoinuser** [Donate4Fun/donate4fun#24]
Hi,

I don't like that my transactions SENT appear in public on my donate4fun profile. Please make an option to hide this information. Thanks.

**Comment by nikicat** [comment]
Done. Now only profile owner can see his transactions. Nevertheless if someone scrapes all donations from the website he will be able to find which of them are yours.
Do you want to have an "anonymous" donation flag, so no one can see who sent a donation?
